/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutPopup: typeof import('@nutui/nutui')['Popup']
  }
}
